import React, { useState, useRef, useEffect } from 'react';
import styles from './Chatbot.module.css';
import { useColorMode } from '@docusaurus/theme-common';

const Chatbot = () => {
  const [messages, setMessages] = useState([
    {
      id: '1',
      text: 'Hello! I\'m your AI assistant for the textbook. How can I help you with the content?',
      isUser: false,
      timestamp: new Date(),
    }
  ]);
  const [inputValue, setInputValue] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const messagesEndRef = useRef(null);
  const inputRef = useRef(null);
  const { colorMode } = useColorMode();

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!inputValue.trim() || isLoading) return;

    // Add user message to chat
    const userMessage = {
      id: Date.now().toString(),
      text: inputValue,
      isUser: true,
      timestamp: new Date(),
    };

    setMessages(prev => [...prev, userMessage]);
    setInputValue('');
    setIsLoading(true);

    try {
      // In a real implementation, this would call the backend API
      // For now, we'll simulate the API call with mock data
      await new Promise(resolve => setTimeout(resolve, 1000)); // Simulate network delay

      // Mock response - in reality this would come from the backend
      const botResponse = {
        id: (Date.now() + 1).toString(),
        text: "This is a simulated response based on the textbook content. In the actual implementation, this would be generated by the RAG system based on your query.",
        isUser: false,
        timestamp: new Date(),
        sources: [
          {
            moduleId: 'module-1-ros2',
            contentId: 'content-1-1',
            title: 'Introduction to ROS 2',
            relevanceScore: 0.92
          },
          {
            moduleId: 'module-1-ros2',
            contentId: 'content-1-2',
            title: 'ROS 2 Nodes, Topics, and Services',
            relevanceScore: 0.85
          }
        ],
        confidence: 0.88
      };

      setMessages(prev => [...prev, botResponse]);
    } catch (error) {
      const errorMessage = {
        id: (Date.now() + 1).toString(),
        text: 'Sorry, I encountered an error processing your request. Please try again.',
        isUser: false,
        timestamp: new Date(),
      };
      setMessages(prev => [...prev, errorMessage]);
    } finally {
      setIsLoading(false);
      if (inputRef.current) {
        inputRef.current.focus();
      }
    }
  };

  return (
    <div className={`${styles.chatbotContainer} ${colorMode === 'dark' ? styles.dark : styles.light}`}>
      <div className={styles.chatHeader}>
        <h3>Textbook AI Assistant</h3>
        <p>Ask questions about the textbook content</p>
      </div>
      
      <div className={styles.chatMessages}>
        {messages.map((message) => (
          <div
            key={message.id}
            className={`${styles.message} ${message.isUser ? styles.userMessage : styles.botMessage}`}
          >
            <div className={styles.messageContent}>
              {message.text}
            </div>
            {message.sources && message.sources.length > 0 && (
              <div className={styles.sources}>
                <h4>Sources:</h4>
                <ul>
                  {message.sources.map((source, idx) => (
                    <li key={idx} className={styles.sourceItem}>
                      <span className={styles.sourceTitle}>{source.title}</span>
                      <span className={styles.relevanceScore}>
                        Relevance: {(source.relevanceScore * 100).toFixed(0)}%
                      </span>
                    </li>
                  ))}
                </ul>
              </div>
            )}
            {message.confidence !== undefined && (
              <div className={styles.confidence}>
                Confidence: {(message.confidence * 100).toFixed(0)}%
              </div>
            )}
          </div>
        ))}
        {isLoading && (
          <div className={`${styles.message} ${styles.botMessage}`}>
            <div className={styles.typingIndicator}>
              <span></span>
              <span></span>
              <span></span>
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>
      
      <form onSubmit={handleSubmit} className={styles.chatInputForm}>
        <input
          ref={inputRef}
          type="text"
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          placeholder="Ask a question about the textbook content..."
          className={styles.chatInput}
          disabled={isLoading}
        />
        <button 
          type="submit" 
          className={styles.chatSubmitButton}
          disabled={isLoading || !inputValue.trim()}
        >
          {isLoading ? 'Sending...' : 'Send'}
        </button>
      </form>
    </div>
  );
};

export default Chatbot;